### ISSUE TITLE
Fail to download on some artifacts

### ISSUE THREAD

**Issue by RMPR** [RMPR/brows3rs#3]

**Comment by vawale** [comment]
error message:
![image](https://github.com/user-attachments/assets/36572bf3-5032-4a0d-9443-f5e7186abcf5)

**Comment by vawale** [comment]
Error: Os { code: 18, kind: CrossesDevices, message: "Invalid cross-device link" }

**Comment by vawale** [comment]
Fixed with https://github.com/RMPR/brows3rs/commit/489848a4d6616e54eb866618eec943259be6e3a7
