### ISSUE TITLE
Allow downloading to existing folder

### ISSUE THREAD

**Issue by johningve** [RMPR/brows3rs#4]
https://github.com/RMPR/brows3rs/blob/170e5b9d5a235e635dc87b1e1e6af934138a5bb2/crates/buckets/src/s3buckets.rs#L191

I find myself wanting to download artifacts to the current folder most often, but doing so results in an error.

```
downloader <url> download -d .
```

I think it should optionally be allowed to overwrite existing files

**Comment by RMPR** [comment]
I agree and even think it should be the default like wget, curl, mv, ... but @vawale doesn't.

**Comment by vawale** [comment]
We can add an argument for this and make it default.

**Comment by RMPR** [comment]
New release with the changes 

https://github.com/RMPR/brows3rs/releases/tag/v0.1.1

**Comment by johningve** [comment]
As a token of my appreciation, I have awarded *1 star*.
